
-- These statements will add some additional defaults to the columns already in the store

-- These SQL statements will drop all the old foreign keys and update with new keys as needed and with a standard naming protocol

-- It also renames the primary keys to the new naming protocol

-- These are the constraint names used in the SQL creation scripts from CFWebstore 5. 
-- If you upscaled from Access you may need to use the constraint names found in the MySQL scripts

BEGIN TRANSACTION

Exec sp_rename 'aaaaaAccessKeys1_PK', 'AccessKey_PK', 'OBJECT';
Exec sp_rename 'aaaaaAccount1_PK', 'Account_PK', 'OBJECT';
Exec sp_rename 'aaaaaAffiliates1_PK', 'Affiliate_PK', 'OBJECT';
Exec sp_rename 'aaaaaCardData1_PK', 'CardData_PK', 'OBJECT';
Exec sp_rename 'aaaaaCatCore1_PK', 'CatCore_PK', 'OBJECT';
Exec sp_rename 'aaaaaCategories1_PK', 'Categories_PK', 'OBJECT';
Exec sp_rename 'aaaaaCCProcess1_PK', 'CCProcess_PK', 'OBJECT';
Exec sp_rename 'aaaaaCertificates1_PK', 'Certificates_PK', 'OBJECT';
Exec sp_rename 'aaaaaColors1_PK', 'Colors_PK', 'OBJECT';
Exec sp_rename 'aaaaaCountries1_PK', 'Countries_PK', 'OBJECT';
Exec sp_rename 'aaaaaCreditCards1_PK', 'CreditCards_PK', 'OBJECT';
Exec sp_rename 'aaaaaCustomers1_PK', 'Customers_PK', 'OBJECT';
Exec sp_rename 'aaaaaDiscounts1_PK', 'Discounts_PK', 'OBJECT';
Exec sp_rename 'aaaaaFeature_Category1_PK', 'Feature_Category_PK', 'OBJECT';
Exec sp_rename 'aaaaaFeature_Item1_PK', 'Feature_Item_PK', 'OBJECT';
Exec sp_rename 'aaaaaFeature_product1_PK', 'Feature_Product_PK', 'OBJECT';
Exec sp_rename 'aaaaaFeatures1_PK', 'Features_PK', 'OBJECT';
Exec sp_rename 'aaaaaGroups1_PK', 'Groups_PK', 'OBJECT';
Exec sp_rename 'aaaaaIntershipper1_PK', 'Intershipper_PK', 'OBJECT';
Exec sp_rename 'aaaaaLocales1_PK', 'Locales_PK', 'OBJECT';
Exec sp_rename 'aaaaaLocalTax1_PK', 'LocalTax_PK', 'OBJECT';
Exec sp_rename 'aaaaaMemberships1_PK', 'Memberships_PK', 'OBJECT';
Exec sp_rename 'aaaaaOrder_No1_PK', 'Order_No_PK', 'OBJECT';
Exec sp_rename 'aaaaaOrder_PO1_PK', 'Order_PO_PK', 'OBJECT';
Exec sp_rename 'aaaaaOrderSettings1_PK', 'OrderSettings_PK', 'OBJECT';
Exec sp_rename 'aaaaaPages1_PK', 'Pages_PK', 'OBJECT';
Exec sp_rename 'aaaaaPicklists1_PK', 'PickLists_PK', 'OBJECT';
Exec sp_rename 'aaaaaProdAddons1_PK', 'ProdAddons_PK', 'OBJECT';
Exec sp_rename 'aaaaaProduct_Category1_PK', 'Product_Category_PK', 'OBJECT';
Exec sp_rename 'aaaaaProduct_Images1_PK', 'Product_Images_PK', 'OBJECT';
Exec sp_rename 'aaaaaProduct_Item1_PK', 'Product_Item_PK', 'OBJECT';
Exec sp_rename 'aaaaaProducts1_PK', 'Products_PK', 'OBJECT';
Exec sp_rename 'aaaaaSettings1_PK', 'Settings_PK', 'OBJECT';
Exec sp_rename 'aaaaaShipping1_PK', 'Shipping_PK', 'OBJECT';
Exec sp_rename 'aaaaaShipSettings1_PK', 'ShipSettings_PK', 'OBJECT';
Exec sp_rename 'aaaaaStates1_PK', 'States_PK', 'OBJECT';
Exec sp_rename 'aaaaaStdAddons1_PK', 'StdAddons_PK', 'OBJECT';
Exec sp_rename 'aaaaaStdOptions1_PK', 'StdOptions_PK', 'OBJECT';
Exec sp_rename 'aaaaaTempBasket1_PK', 'TempBasket_PK', 'OBJECT';
Exec sp_rename 'aaaaaTempCustomer1_PK', 'TempCustomer_PK', 'OBJECT';
Exec sp_rename 'aaaaaTempOrder1_PK', 'TempOrder_PK', 'OBJECT';
Exec sp_rename 'aaaaaTempShipTo1_PK', 'TempShipTo_PK', 'OBJECT';
Exec sp_rename 'aaaaaUPS_Settings1_PK', 'UPS_Settings_PK', 'OBJECT';
Exec sp_rename 'aaaaaUsers1_PK', 'Users_PK', 'OBJECT';
Exec sp_rename 'aaaaaUserSettings1_PK', 'UserSettings_PK', 'OBJECT';
Exec sp_rename 'aaaaaWishList1_PK', 'WishList_PK', 'OBJECT';

ALTER TABLE CardData DROP CONSTRAINT CardData_FK00;
ALTER TABLE Categories DROP CONSTRAINT Categories_FK00;
ALTER TABLE Categories DROP CONSTRAINT ColorsCategories;
ALTER TABLE Feature_Category DROP CONSTRAINT Feature_Category_FK00;
ALTER TABLE Feature_Category DROP CONSTRAINT Feature_Category_FK01;
ALTER TABLE Feature_Item DROP CONSTRAINT Feature_Item_FK00;
ALTER TABLE Feature_Item DROP CONSTRAINT Feature_Item_FK01;
ALTER TABLE Feature_Product DROP CONSTRAINT Feature_product_FK00;
ALTER TABLE Feature_Product DROP CONSTRAINT Feature_product_FK01;
ALTER TABLE Features DROP CONSTRAINT Features_FK00;
ALTER TABLE Features DROP CONSTRAINT ColorsFeatures;
ALTER TABLE Memberships DROP CONSTRAINT Memberships_FK00;
ALTER TABLE Order_No DROP CONSTRAINT Order_No_FK00;
ALTER TABLE Order_PO DROP CONSTRAINT Order_PO_FK00;
ALTER TABLE Pages DROP CONSTRAINT Pages_FK00;
ALTER TABLE Pages DROP CONSTRAINT Pages_FK01;
ALTER TABLE ProdAddons DROP CONSTRAINT ProdAddons_FK00;
ALTER TABLE ProdDisc DROP CONSTRAINT ProdDisc_FK00;
ALTER TABLE Product_Category DROP CONSTRAINT Product_Category_FK00;
ALTER TABLE Product_Category DROP CONSTRAINT Product_Category_FK01;
ALTER TABLE Product_Images DROP CONSTRAINT Product_Images_FK00;
ALTER TABLE Product_Item DROP CONSTRAINT Product_Item_FK00;
ALTER TABLE Product_Item DROP CONSTRAINT Product_Item_FK01;
ALTER TABLE Products DROP CONSTRAINT Products_FK00;
ALTER TABLE WishList DROP CONSTRAINT WishList_FK00;


ALTER TABLE CardData ADD CONSTRAINT Customers_CardData_FK FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID);
ALTER TABLE Categories ADD CONSTRAINT CatCore_Categories_FK FOREIGN KEY (CatCore_ID) REFERENCES CatCore(CatCore_ID);
ALTER TABLE Feature_Category ADD CONSTRAINT Categories_Feature_Category_FK FOREIGN KEY (Category_ID) REFERENCES Categories(Category_ID);
ALTER TABLE Feature_Category ADD CONSTRAINT Features_Feature_Category_FK FOREIGN KEY (Feature_ID) REFERENCES Features(Feature_ID);
ALTER TABLE Feature_Item ADD CONSTRAINT Features_Feature_Item_FK FOREIGN KEY (Feature_ID) REFERENCES Features(Feature_ID);
ALTER TABLE Feature_Item ADD CONSTRAINT Features_Feature_Item_FK_2 FOREIGN KEY (Item_ID) REFERENCES Features(Feature_ID);
ALTER TABLE Feature_Product ADD CONSTRAINT Features_Feature_Product_FK FOREIGN KEY (Feature_ID) REFERENCES Features(Feature_ID);
ALTER TABLE Feature_Product ADD CONSTRAINT Products_Feature_Product_FK FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID);
ALTER TABLE Features ADD CONSTRAINT Users_Features_FK FOREIGN KEY (User_ID) REFERENCES Users(User_ID);
ALTER TABLE Memberships ADD CONSTRAINT Users_Memberships_FK FOREIGN KEY (User_ID) REFERENCES Users(User_ID);
ALTER TABLE Order_No ADD CONSTRAINT Customers_Order_No_FK FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID);
ALTER TABLE Order_PO ADD CONSTRAINT Order_No_Order_PO_FK FOREIGN KEY (Order_No) REFERENCES Order_No(Order_No);
ALTER TABLE Pages ADD CONSTRAINT CatCore_Pages_FK FOREIGN KEY (CatCore_ID) REFERENCES CatCore(CatCore_ID);
ALTER TABLE ProdAddons ADD CONSTRAINT Products_ProdAddons_FK FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID);
ALTER TABLE ProdDisc ADD CONSTRAINT Products_ProdDisc_FK FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID);
ALTER TABLE Product_Category ADD CONSTRAINT Categories_Product_Category_FK FOREIGN KEY (Category_ID) REFERENCES Categories(Category_ID);
ALTER TABLE Product_Category ADD CONSTRAINT Products_Product_Category_FK FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID);
ALTER TABLE Product_Images ADD CONSTRAINT Products_Product_Images_FK FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID);
ALTER TABLE Product_Item ADD CONSTRAINT Products_Product_Item_FK FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID);
ALTER TABLE Product_Item ADD CONSTRAINT Products_Product_Item_FK_2 FOREIGN KEY (Item_ID) REFERENCES Products(Product_ID);
ALTER TABLE WishList ADD CONSTRAINT Users_WishList_FK FOREIGN KEY (User_ID) REFERENCES Users(User_ID);


-- These SQL statements will drop all the old indexes and update with new indexes as needed and with a standard naming protocol

CREATE INDEX Account_Customer_ID_Idx ON Account (Customer_ID );
CREATE INDEX Account_User_ID_Idx ON Account (User_ID );
CREATE INDEX Affiliate_AffCode_Idx ON Affiliates (AffCode );
CREATE INDEX CardData_Customer_ID_Idx ON CardData (Customer_ID );
CREATE INDEX Categories_CatCore_ID_Idx ON Categories (CatCore_ID );
CREATE INDEX Category_Color_ID_Idx ON Categories (Color_ID );
CREATE INDEX Category_Parent_ID_Idx ON Categories (Parent_ID );
CREATE INDEX Certificates_Cert_Code_Idx ON Certificates (Cert_Code );
CREATE UNIQUE INDEX Countries_Abbrev_Idx ON Countries (Abbrev );
CREATE INDEX Countries_Shipping_Idx ON Countries (Shipping );
CREATE INDEX Customers_User_ID_Idx ON Customers (User_ID );
CREATE INDEX Discounts_Coup_Code_Idx ON Discounts (Coup_Code );
CREATE INDEX Feature_Category_Category_ID_Idx ON Feature_Category (Category_ID );
CREATE INDEX Feature_Category_Feature_ID_Idx ON Feature_Category (Feature_ID );
CREATE INDEX Feature_Item_Feature_ID_Idx ON Feature_Item (Feature_ID );
CREATE INDEX Feature_Item_Item_ID_Idx ON Feature_Item (Item_ID );
CREATE INDEX Feature_Product_Feature_ID_Idx ON Feature_Product (Feature_ID );
CREATE INDEX Feature_Product_Product_ID_Idx ON Feature_Product (Product_ID );
CREATE INDEX Features_AccessKey_Idx ON Features (AccessKey );
CREATE INDEX Features_Color_ID_Idx ON Features (Color_ID );
CREATE INDEX Features_User_ID_Idx ON Features (User_ID );
CREATE INDEX Groups_Name_Idx ON Groups (Name );
CREATE INDEX LocalTax_ZipCode_Idx ON LocalTax (ZipCode );
CREATE UNIQUE INDEX Locales_Name_Idx ON Locales (Name );
CREATE INDEX Memberships_AccessKey_ID_Idx ON Memberships (AccessKey_ID );
CREATE INDEX Memberships_User_ID_Idx ON Memberships (User_ID );
CREATE INDEX Order_No_Coup_Code_Idx ON Order_No (Coup_Code );
CREATE INDEX Order_No_Customer_ID_Idx ON Order_No (Customer_ID );
CREATE INDEX Order_No_User_ID_Idx ON Order_No (User_ID );
CREATE INDEX Order_PO_Account_ID_Idx ON Order_PO (Account_ID );
CREATE INDEX Order_PO_Order_No_Idx ON Order_PO (Order_No );
CREATE INDEX Pages_AccessKey_Idx ON Pages (AccessKey );
CREATE INDEX Pages_CatCore_ID_Idx ON Pages (CatCore_ID );
CREATE INDEX Pages_Color_ID_Idx ON Pages (Color_ID );
CREATE INDEX ProdAddons_Product_ID_Idx ON ProdAddons (Product_ID );
CREATE INDEX ProdAddons_Standard_ID_Idx ON ProdAddons (Standard_ID );
CREATE INDEX Product_Category_Category_ID_Idx ON Product_Category (Category_ID );
CREATE INDEX Product_Category_Product_ID_Idx ON Product_Category (Product_ID );
CREATE INDEX Product_Images_Product_ID_Idx ON Product_Images (Product_ID );
CREATE INDEX Product_Item_Item_ID_Idx ON Product_Item (Item_ID );
CREATE INDEX Product_Item_Product_ID_Idx ON Product_Item (Product_ID );
CREATE INDEX Products_AccessKey_Idx ON Products (AccessKey );
CREATE INDEX Products_Account_ID_Idx ON Products (Account_ID );
CREATE INDEX Products_Highlight_Idx ON Products (Highlight );
CREATE INDEX Products_NumInStock_Idx ON Products (NumInStock );
CREATE INDEX TempBasket_BasketNum_Idx ON TempBasket (BasketNum );
CREATE INDEX TempBasket_Product_ID_Idx ON TempBasket (Product_ID );
CREATE INDEX Users_Account_ID_Idx ON Users (Account_ID );
CREATE INDEX Users_Affiliate_ID_Idx ON Users (Affiliate_ID );
CREATE INDEX Users_Customer_ID_Idx ON Users (Customer_ID );
CREATE INDEX Users_Group_ID_Idx ON Users (Group_ID );
CREATE INDEX WishList_Product_ID_Idx ON WishList (Product_ID );
CREATE INDEX WishList_User_ID_Idx ON WishList (User_ID );


DROP INDEX AccessKeys.Privilege_ID;
DROP INDEX Account.Contact_ID;
DROP INDEX Account.User_ID;
DROP INDEX Affiliates.AffCode;
DROP INDEX CardData.Customer_ID;
DROP INDEX CardData.CustomersCardData;
DROP INDEX CatCore.CatFormat_ID;
DROP INDEX Categories.CatCoreCategories;
DROP INDEX Categories.CatFormat_ID;
DROP INDEX Categories.Parent_ID;
DROP INDEX Categories.Subcategory_ID;
DROP INDEX Certificates.Cert_Code;
DROP INDEX Certificates.Cert_ID;
DROP INDEX Countries.Abbrev;
DROP INDEX Countries.Shipping;
DROP INDEX Customers.User_ID;
DROP INDEX Discounts.Coup_Code;
DROP INDEX Feature_Category.CategoriesFeature_Category;
DROP INDEX Feature_Category.Category_ID;
DROP INDEX Feature_Category.Event_category_ID;
DROP INDEX Feature_Category.Event_ID;
DROP INDEX Feature_Category.FeaturesFeature_Category;
DROP INDEX Feature_Item.Feature_ID;
DROP INDEX Feature_Item.Feature_Item_ID1;
DROP INDEX Feature_Item.FeaturesFeature_Item;
DROP INDEX Feature_Item.FeaturesFeature_Item1;
DROP INDEX Feature_Item.Item_ID;
DROP INDEX Feature_Product.Category_ID;
DROP INDEX Feature_Product.FeaturesFeature_product;
DROP INDEX Feature_Product.ID;
DROP INDEX Feature_Product.Item_Number;
DROP INDEX Feature_Product.ProductsFeature_product;
DROP INDEX Features.access_Key;
DROP INDEX Features.contributor_id;
DROP INDEX Features.Feature_id;
DROP INDEX Features.Palette_ID;
DROP INDEX Features.UsersFeatures;
DROP INDEX Groups.PK_GroupName;
DROP INDEX Intershipper.UserID;
DROP INDEX LocalTax.Local_ID;
DROP INDEX LocalTax.ZipCode;
DROP INDEX Locales.Name;
DROP INDEX Memberships.Membership_ID;
DROP INDEX Memberships.Order_ID;
DROP INDEX Memberships.Privilege_ID;
DROP INDEX Memberships.Product_ID;
DROP INDEX Memberships.User_ID;
DROP INDEX Memberships.UsersMemberships;
DROP INDEX OrderSettings.BaseOrderNum;
DROP INDEX Order_No.Card_ID;
DROP INDEX Order_No.Cert_Code;
DROP INDEX Order_No.Coup_Code;
DROP INDEX Order_No.Customer_ID;
DROP INDEX Order_No.CustomersOrder_No;
DROP INDEX Order_No.ID;
DROP INDEX Order_No.User_ID;
DROP INDEX Order_PO.Account_ID;
DROP INDEX Order_PO.Order_no_ID;
DROP INDEX Order_PO.Order_NoOrder_PO;
DROP INDEX Order_PO.Ship_tracker_id;
DROP INDEX Pages.accesskey;
DROP INDEX Pages.catcore_ID;
DROP INDEX Pages.CatCorePages;
DROP INDEX Pages.Color_ID;
DROP INDEX PickLists.picklist_id;
DROP INDEX ProdAddons.Product_ID;
DROP INDEX ProdAddons.ProductsProdAddons;
DROP INDEX ProdAddons.Standard_ID;
DROP INDEX ProdDisc.Product_id;
DROP INDEX ProdDisc.ProductsProdDisc;
DROP INDEX ProdDisc.ProdVolume_id;
DROP INDEX Product_Category.CategoriesProduct_Category;
DROP INDEX Product_Category.Category_ID;
DROP INDEX Product_Category.ID;
DROP INDEX Product_Category.Item_Number;
DROP INDEX Product_Category.ProductsProduct_Category;
DROP INDEX Product_Images.ProductsProduct_Images;
DROP INDEX Product_Images.Profile_ID;
DROP INDEX Product_Images.Profile_image_id;
DROP INDEX Product_Item.Category_ID;
DROP INDEX Product_Item.ID;
DROP INDEX Product_Item.Item_Number;
DROP INDEX Product_Item.ProductsProduct_Item;
DROP INDEX Product_Item.ProductsProduct_Item1;
DROP INDEX Products.accessKey;
DROP INDEX Products.Account_ID;
DROP INDEX Products.mfg_account_ID;
DROP INDEX Products.num_days;
DROP INDEX Products.NumInStock;
DROP INDEX Products.Product_ID;
DROP INDEX Settings.color_id;
DROP INDEX Settings.SettingID;
DROP INDEX ShipSettings.freeship_shipid;
DROP INDEX StdAddons.StdID;
DROP INDEX StdOptions.StdID;
DROP INDEX TempBasket.Basket_Idx;
DROP INDEX TempBasket.Product_ID;
DROP INDEX UPS_Settings.UPS_ID;
DROP INDEX UserSettings.ID;
DROP INDEX Users.Account_id;
DROP INDEX Users.Affiliate_ID;
DROP INDEX Users.Customer_ID;
DROP INDEX Users.Level;
DROP INDEX Users.UserID;
DROP INDEX WishList.ItemNum;
DROP INDEX WishList.ListNum;
DROP INDEX WishList.NumDesired;
DROP INDEX WishList.Product_ID;
DROP INDEX WishList.User_ID;
DROP INDEX WishList.UsersWishList;

COMMIT

