
-- Some additional changes for the schema you may need. 
-- Change all integers to int (if bigint before) and makes all tables InnoDB to use foreign keys


ALTER TABLE `AccessKeys` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `AccessKeys` MODIFY COLUMN `AccessKey_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Account` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Account` MODIFY COLUMN `Account_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Account` MODIFY COLUMN `User_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Account` MODIFY COLUMN `Customer_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Affiliates` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Affiliates` MODIFY COLUMN `Affiliate_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Affiliates` MODIFY COLUMN `AffCode` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `CardData` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `CardData` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `CardData` MODIFY COLUMN `Customer_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `CatCore` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `CatCore` MODIFY COLUMN `CatCore_ID` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `Categories` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Categories` MODIFY COLUMN `Category_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Categories` MODIFY COLUMN `Parent_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Categories` MODIFY COLUMN `CatCore_ID` int(11) NOT NULL DEFAULT 1 ;
ALTER TABLE `Categories` MODIFY COLUMN `AccessKey` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Categories` MODIFY COLUMN `Priority` int(11) NOT NULL DEFAULT 9999 ;
ALTER TABLE `CCProcess` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `CCProcess` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Certificates` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Certificates` MODIFY COLUMN `Cert_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Colors` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Colors` MODIFY COLUMN `Color_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Countries` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Countries` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Countries` MODIFY COLUMN `Shipping` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `CreditCards` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `CreditCards` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Customers` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Customers` MODIFY COLUMN `Customer_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Customers` MODIFY COLUMN `User_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `CustomNames` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `CustomNames` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Discounts` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Discounts` MODIFY COLUMN `Discount_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Discounts` MODIFY COLUMN `Type1` int(11) NOT NULL DEFAULT 1 ;
ALTER TABLE `Discounts` MODIFY COLUMN `Type2` int(11) NOT NULL DEFAULT 1 ;
ALTER TABLE `Discounts` MODIFY COLUMN `Type3` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Discounts` MODIFY COLUMN `Type4` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Discounts` MODIFY COLUMN `Type5` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Feature_Category` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Feature_Category` MODIFY COLUMN `Feature_Category_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Feature_Category` MODIFY COLUMN `Feature_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Feature_Category` MODIFY COLUMN `Category_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Feature_Item` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Feature_Item` MODIFY COLUMN `Feature_Item_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Feature_Item` MODIFY COLUMN `Feature_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Feature_Item` MODIFY COLUMN `Item_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Feature_Product` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Feature_Product` MODIFY COLUMN `Feature_Product_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Feature_Product` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Feature_Product` MODIFY COLUMN `Feature_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Features` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Features` MODIFY COLUMN `Feature_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Features` MODIFY COLUMN `User_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Features` MODIFY COLUMN `Priority` int(11) NULL DEFAULT 9999 ;
ALTER TABLE `Features` MODIFY COLUMN `AccessKey` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Features` MODIFY COLUMN `Color_ID` int(11) NULL ;
ALTER TABLE `Groups` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Groups` MODIFY COLUMN `Group_ID` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `Intershipper` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Intershipper` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `IntShipTypes` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `IntShipTypes` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Locales` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Locales` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `LocalTax` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `LocalTax` MODIFY COLUMN `Local_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Memberships` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Memberships` MODIFY COLUMN `Membership_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Memberships` MODIFY COLUMN `User_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Memberships` MODIFY COLUMN `Order_ID` int(11) NULL ;
ALTER TABLE `Memberships` MODIFY COLUMN `Product_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Memberships` MODIFY COLUMN `Time_Count` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Memberships` MODIFY COLUMN `Access_Count` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Memberships` MODIFY COLUMN `Access_Used` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Order_No` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Order_No` MODIFY COLUMN `Order_No` int(11) NOT NULL auto_increment ;
ALTER TABLE `Order_No` MODIFY COLUMN `Customer_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Order_No` MODIFY COLUMN `User_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Order_No` MODIFY COLUMN `Card_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Order_No` MODIFY COLUMN `ShipTo` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Order_No` MODIFY COLUMN `Affiliate` int(11) NULL ;
ALTER TABLE `Order_No` MODIFY COLUMN `Printed` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Order_PO` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Order_PO` MODIFY COLUMN `Order_PO_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Order_PO` MODIFY COLUMN `Order_No` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Order_PO` MODIFY COLUMN `Account_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Orders` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Orders` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Orders` MODIFY COLUMN `Order_No` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Orders` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Orders` MODIFY COLUMN `Quantity` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Orders` MODIFY COLUMN `OptQuant` int(11) NULL ;
ALTER TABLE `Orders` MODIFY COLUMN `Dropship_Account_ID` int(11) NULL ;
ALTER TABLE `Orders` MODIFY COLUMN `Dropship_Qty` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Orders` MODIFY COLUMN `Dropship_Cost` int(11) NULL DEFAULT 0 ;
ALTER TABLE `OrderSettings` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `OrderSettings` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `OrderSettings` MODIFY COLUMN `BaseOrderNum` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `OrderSettings` MODIFY COLUMN `MinTotal` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Pages` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Pages` MODIFY COLUMN `Page_ID` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `Pages` MODIFY COLUMN `CatCore_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Pages` MODIFY COLUMN `Color_ID` int(11) NULL ;
ALTER TABLE `Pages` MODIFY COLUMN `AccessKey` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Pages` MODIFY COLUMN `Priority` int(11) NULL DEFAULT 9999 ;
ALTER TABLE `Pages` MODIFY COLUMN `Parent_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Pages` MODIFY COLUMN `Title_Priority` int(11) NULL DEFAULT 0 ;
ALTER TABLE `PickLists` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `PickLists` MODIFY COLUMN `Picklist_id` int(11) NOT NULL auto_increment ;
ALTER TABLE `ProdAddons` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `ProdAddons` MODIFY COLUMN `Addon_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `ProdAddons` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdAddons` MODIFY COLUMN `Standard_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdAddons` MODIFY COLUMN `Priority` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdCustom` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `ProdCustom` MODIFY COLUMN `Custom_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `ProdCustom` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdDisc` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `ProdDisc` MODIFY COLUMN `ProdDisc_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `ProdDisc` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdDisc` MODIFY COLUMN `QuantFrom` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdDisc` MODIFY COLUMN `QuantTo` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdOptions` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `ProdOptions` MODIFY COLUMN `Option_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `ProdOptions` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdOptions` MODIFY COLUMN `Standard_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `ProdOptions` MODIFY COLUMN `Priority` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Product_Category` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Product_Category` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Product_Category` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Product_Category` MODIFY COLUMN `Category_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Product_Images` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Product_Images` MODIFY COLUMN `Product_Image_ID` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `Product_Images` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Product_Images` MODIFY COLUMN `File_Size` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Product_Images` MODIFY COLUMN `Priority` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Product_Item` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Product_Item` MODIFY COLUMN `Product_Item_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Product_Item` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Product_Item` MODIFY COLUMN `Item_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Products` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Products` MODIFY COLUMN `Product_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Products` MODIFY COLUMN `AccessKey` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `Color_ID` int(11) NULL ;
ALTER TABLE `Products` MODIFY COLUMN `Priority` int(11) NOT NULL DEFAULT 9999 ;
ALTER TABLE `Products` MODIFY COLUMN `NumInStock` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `NumOptions` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `NumAddons` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `OptQuant` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `Reorder_Level` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `Account_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `Mfg_Account_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `Processing` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `Pass_Thru` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `Access_Count` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Products` MODIFY COLUMN `Num_Days` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Settings` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Settings` MODIFY COLUMN `SettingID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Settings` MODIFY COLUMN `CColumns` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Settings` MODIFY COLUMN `PColumns` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Settings` MODIFY COLUMN `MaxProds` int(11) NOT NULL DEFAULT 9999 ;
ALTER TABLE `Settings` MODIFY COLUMN `ProdRoot` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Settings` MODIFY COLUMN `FeatureRoot` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Settings` MODIFY COLUMN `Email_Port` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Shipping` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Shipping` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `ShipSettings` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `ShipSettings` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `ShipSettings` MODIFY COLUMN `Freeship_Min` int(11) NULL DEFAULT 0 ;
ALTER TABLE `ShipTypes` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `ShipTypes` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `States` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `StdAddons` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `StdAddons` MODIFY COLUMN `Std_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `StdOptions` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `StdOptions` MODIFY COLUMN `Std_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Taxes` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Taxes` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `TempBasket` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `TempBasket` MODIFY COLUMN `Product_ID` int(11) NULL ;
ALTER TABLE `TempBasket` MODIFY COLUMN `Quantity` int(11) NULL;
ALTER TABLE `TempBasket` MODIFY COLUMN `OptQuant` int(11) NULL;
ALTER TABLE `TempBasket` MODIFY COLUMN `Discount` int(11) NULL;
ALTER TABLE `TempCustomer` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `TempOrder` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `TempOrder` MODIFY COLUMN `Affiliate` int(11) NULL DEFAULT 0 ;
ALTER TABLE `TempShipTo` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `UPS_CanadaZones` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `UPS_Settings` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `UPS_Settings` MODIFY COLUMN `UPS_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `UPSZones` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Users` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `Users` MODIFY COLUMN `User_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `Users` MODIFY COLUMN `Customer_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Users` MODIFY COLUMN `ShipTo` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Users` MODIFY COLUMN `Group_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `Users` MODIFY COLUMN `Account_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Users` MODIFY COLUMN `Affiliate_ID` int(11) NULL DEFAULT 0 ;
ALTER TABLE `Users` MODIFY COLUMN `CurrentBalance` int(11) NULL DEFAULT 0 ;
ALTER TABLE `UserSettings` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `UserSettings` MODIFY COLUMN `ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `USPS` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `USPS` MODIFY COLUMN `USPS_ID` int(11) NOT NULL auto_increment ;
ALTER TABLE `WishList` DEFAULT CHARACTER SET latin1, COLLATE latin1_swedish_ci, TYPE=InnoDB;
ALTER TABLE `WishList` MODIFY COLUMN `User_ID` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `WishList` MODIFY COLUMN `ListNum` int(11) NOT NULL DEFAULT 1 ;
ALTER TABLE `WishList` MODIFY COLUMN `ItemNum` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `WishList` MODIFY COLUMN `Product_ID` int(11) NOT NULL DEFAULT 0 ;
ALTER TABLE `WishList` MODIFY COLUMN `NumDesired` int(11) NULL DEFAULT 0 ;

