SET FOREIGN_KEY_CHECKS=0;
-- These statements will add some additional defaults to the columns already in the store

ALTER TABLE `AccessKeys` CHANGE COLUMN `System` `System` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Account` CHANGE COLUMN `Directory_Live` `Directory_Live` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `CatCore` CHANGE COLUMN `Category` `Category` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `CatCore` CHANGE COLUMN `Products` `Products` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `CatCore` CHANGE COLUMN `Features` `Features` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `CatCore` CHANGE COLUMN `Page` `Page` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Features` CHANGE COLUMN `Display` `Display` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Features` CHANGE COLUMN `Approved` `Approved` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Features` CHANGE COLUMN `Highlight` `Highlight` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Features` CHANGE COLUMN `Display_Title` `Display_Title` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Groups` CHANGE COLUMN `Wholesale` `Wholesale` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Memberships` CHANGE COLUMN `Valid` `Valid` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `OrderSettings` CHANGE COLUMN `StoreCardInfo` `StoreCardInfo` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `OrderSettings` CHANGE COLUMN `UseCVV2` `UseCVV2` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `OrderSettings` CHANGE COLUMN `MinTotal` `MinTotal` integer (11) NOT NULL  DEFAULT '0';
ALTER TABLE `OrderSettings` CHANGE COLUMN `NoGuests` `NoGuests` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `OrderSettings` CHANGE COLUMN `UseBilling` `UseBilling` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Order_No` CHANGE COLUMN `Void` `Void` tinyint (1) DEFAULT '0';
ALTER TABLE `Order_No` CHANGE COLUMN `OrderDisc` `OrderDisc` double  NOT NULL  DEFAULT '0';
ALTER TABLE `Order_No` CHANGE COLUMN `Credits` `Credits` double  NOT NULL  DEFAULT '0';
ALTER TABLE `Order_No` CHANGE COLUMN `AddonTotal` `AddonTotal` double  NOT NULL  DEFAULT '0';
ALTER TABLE `Order_No` CHANGE COLUMN `AdminCredit` `AdminCredit` double  NOT NULL  DEFAULT '0';
ALTER TABLE `Order_No` CHANGE COLUMN `Paid` `Paid` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Order_PO` CHANGE COLUMN `PO_Open` `PO_Open` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Pages` CHANGE COLUMN `Display` `Display` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Pages` CHANGE COLUMN `System` `System` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `ProdAddons` CHANGE COLUMN `Priority` `Priority` integer (11) NOT NULL  DEFAULT '9999';
ALTER TABLE `ProdAddons` CHANGE COLUMN `ProdMult` `ProdMult` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `ProdAddons` CHANGE COLUMN `Required` `Required` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `ProdDisc` CHANGE COLUMN `Product_ID` `Product_ID` integer (11) NOT NULL  DEFAULT '0';
ALTER TABLE `ProdDisc` CHANGE COLUMN `ProdDisc_ID` `ProdDisc_ID` integer (11) NOT NULL  DEFAULT '0';
ALTER TABLE `Products` CHANGE COLUMN `Hot` `Hot` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Products` CHANGE COLUMN `Discounts` `Discounts` varchar (255);
ALTER TABLE `Products` CHANGE COLUMN `VertOptions` `VertOptions` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Settings` CHANGE COLUMN `Wishlists` `Wishlists` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Settings` CHANGE COLUMN `AllowWholesale` `AllowWholesale` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Settings` CHANGE COLUMN `UseVerity` `UseVerity` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `Settings` CHANGE COLUMN `Admin_New_Window` `Admin_New_Window` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `StdAddons` CHANGE COLUMN `Std_Price` `Std_Price` double  NOT NULL  DEFAULT '0';
ALTER TABLE `StdAddons` CHANGE COLUMN `Std_Weight` `Std_Weight` double  NOT NULL  DEFAULT '0';
ALTER TABLE `StdAddons` CHANGE COLUMN `Std_Required` `Std_Required` tinyint (1) DEFAULT '0';
ALTER TABLE `TempBasket` CHANGE COLUMN `Product_ID` `Product_ID` integer (11) NOT NULL  DEFAULT '0';
ALTER TABLE `TempBasket` CHANGE COLUMN `Price` `Price` double  DEFAULT '0';
ALTER TABLE `TempBasket` CHANGE COLUMN `Weight` `Weight` double  DEFAULT '0';
ALTER TABLE `TempBasket` CHANGE COLUMN `Quantity` `Quantity` integer (11) DEFAULT '0';
ALTER TABLE `TempBasket` CHANGE COLUMN `OptQuant` `OptQuant` integer (11) NOT NULL  DEFAULT '0';
ALTER TABLE `TempBasket` CHANGE COLUMN `Discount` `Discount` integer (11) DEFAULT '0';
ALTER TABLE `TempBasket` CHANGE COLUMN `QuantDisc` `QuantDisc` double  DEFAULT '0';
ALTER TABLE `TempCustomer` CHANGE COLUMN `ShipToYes` `ShipToYes` tinyint (1) DEFAULT '0';
ALTER TABLE `TempOrder` CHANGE COLUMN `OrderTotal` `OrderTotal` double  DEFAULT '0';
ALTER TABLE `TempOrder` CHANGE COLUMN `Tax` `Tax` double  DEFAULT '0';
ALTER TABLE `TempOrder` CHANGE COLUMN `Shipping` `Shipping` double  DEFAULT '0';
ALTER TABLE `TempOrder` CHANGE COLUMN `OrderDisc` `OrderDisc` double  DEFAULT '0';
ALTER TABLE `TempOrder` CHANGE COLUMN `Credits` `Credits` double  DEFAULT '0';
ALTER TABLE `UPS_Settings` CHANGE COLUMN `ResRates` `ResRates` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseRememberMe` `UseRememberMe` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `EmailAsName` `EmailAsName` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseStateList` `UseStateList` tinyint (1) NOT NULL  DEFAULT '1';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseStateBox` `UseStateBox` tinyint (1) NOT NULL  DEFAULT '1';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseCountryList` `UseCountryList` tinyint (1) NOT NULL  DEFAULT '1';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseGroupCode` `UseGroupCode` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseBirthdate` `UseBirthdate` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseTerms` `UseTerms` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseCCard` `UseCCard` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseEmailConf` `UseEmailConf` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseEmailNotif` `UseEmailNotif` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseShipTo` `UseShipTo` tinyint (1) NOT NULL  DEFAULT '1';
ALTER TABLE `UserSettings` CHANGE COLUMN `UseAccounts` `UseAccounts` tinyint (1) NOT NULL  DEFAULT '0';
ALTER TABLE `UserSettings` CHANGE COLUMN `ShowAccount` `ShowAccount` tinyint (1) NOT NULL  DEFAULT '1';
ALTER TABLE `UserSettings` CHANGE COLUMN `ShowDirectory` `ShowDirectory` tinyint (1) NOT NULL  DEFAULT '1';
ALTER TABLE `UserSettings` CHANGE COLUMN `ShowSubscribe` `ShowSubscribe` tinyint (1) NOT NULL  DEFAULT '1';
ALTER TABLE `Users` CHANGE COLUMN `EmailIsBad` `EmailIsBad` tinyint (1) NOT NULL  DEFAULT '0';

-- These SQL statements will drop all the old foreign keys and update with new keys as needed and with a standard naming protocol
-- Foreign key and index names will vary greatly according to how you created your MySQL database
-- You may need to edit these following statements to match names created in your database
-- In some cases, you many not have the foreign keys at all and can just skip all the DROP statements


ALTER TABLE `CardData` DROP FOREIGN KEY `CustomersCardData`;
ALTER TABLE `Categories` DROP FOREIGN KEY `CatCoreCategories`;
ALTER TABLE `Feature_Category` DROP FOREIGN KEY `CategoriesFeature_Category`;
ALTER TABLE `Feature_Category` DROP FOREIGN KEY `FeaturesFeature_Category`;
ALTER TABLE `Feature_Item` DROP FOREIGN KEY `FeaturesFeature_Item`;
ALTER TABLE `Feature_Item` DROP FOREIGN KEY `FeaturesFeature_Item1`;
ALTER TABLE `Feature_Product` DROP FOREIGN KEY `FeaturesFeature_product`;
ALTER TABLE `Feature_Product` DROP FOREIGN KEY `ProductsFeature_product`;
ALTER TABLE `Features` DROP FOREIGN KEY `UsersFeatures`;
ALTER TABLE `Memberships` DROP FOREIGN KEY `UsersMemberships`;
ALTER TABLE `Order_No` DROP FOREIGN KEY `CustomersOrder_No`;
ALTER TABLE `Order_PO` DROP FOREIGN KEY `Order_NoOrder_PO`;
ALTER TABLE `Pages` DROP FOREIGN KEY `CatCorePages`;
ALTER TABLE `ProdAddons` DROP FOREIGN KEY `ProductsProdAddons`;
ALTER TABLE `ProdDisc` DROP FOREIGN KEY `ProductsProdDisc`;
ALTER TABLE `Product_Category` DROP FOREIGN KEY `CategoriesProduct_Category`;
ALTER TABLE `Product_Category` DROP FOREIGN KEY `ProductsProduct_Category`;
ALTER TABLE `Product_Item` DROP FOREIGN KEY `ProductsProduct_Item`;
ALTER TABLE `Product_Item` DROP FOREIGN KEY `ProductsProduct_Item1`;
ALTER TABLE `WishList` DROP FOREIGN KEY `UsersWishList`;

ALTER TABLE `CardData` ADD CONSTRAINT Customers_CardData_FK FOREIGN KEY (Customer_ID) REFERENCES `Customers`(Customer_ID);
ALTER TABLE `Categories` ADD CONSTRAINT CatCore_Categories_FK FOREIGN KEY (CatCore_ID) REFERENCES `CatCore`(CatCore_ID);
ALTER TABLE `Feature_Category` ADD CONSTRAINT Categories_Feature_Category_FK FOREIGN KEY (Category_ID) REFERENCES `Categories`(Category_ID);
ALTER TABLE `Feature_Category` ADD CONSTRAINT Features_Feature_Category_FK FOREIGN KEY (Feature_ID) REFERENCES `Features`(Feature_ID);
ALTER TABLE `Feature_Item` ADD CONSTRAINT Features_Feature_Item_FK FOREIGN KEY (Feature_ID) REFERENCES `Features`(Feature_ID);
ALTER TABLE `Feature_Item` ADD CONSTRAINT Features_Feature_Item_FK_2 FOREIGN KEY (Item_ID) REFERENCES `Features`(Feature_ID);
ALTER TABLE `Feature_Product` ADD CONSTRAINT Features_Feature_Product_FK FOREIGN KEY (Feature_ID) REFERENCES `Features`(Feature_ID);
ALTER TABLE `Feature_Product` ADD CONSTRAINT Products_Feature_Product_FK FOREIGN KEY (Product_ID) REFERENCES `Products`(Product_ID);
ALTER TABLE `Features` ADD CONSTRAINT Users_Features_FK FOREIGN KEY (User_ID) REFERENCES `Users`(User_ID);
ALTER TABLE `Memberships` ADD CONSTRAINT Users_Memberships_FK FOREIGN KEY (User_ID) REFERENCES `Users`(User_ID);
ALTER TABLE `Order_No` ADD CONSTRAINT Customers_Order_No_FK FOREIGN KEY (Customer_ID) REFERENCES `Customers`(Customer_ID);
ALTER TABLE `Order_PO` ADD CONSTRAINT Order_No_Order_PO_FK FOREIGN KEY (Order_No) REFERENCES `Order_No`(Order_No);
ALTER TABLE `Pages` ADD CONSTRAINT CatCore_Pages_FK FOREIGN KEY (CatCore_ID) REFERENCES `CatCore`(CatCore_ID);
ALTER TABLE `ProdAddons` ADD CONSTRAINT Products_ProdAddons_FK FOREIGN KEY (Product_ID) REFERENCES `Products`(Product_ID);
ALTER TABLE `ProdDisc` ADD CONSTRAINT Products_ProdDisc_FK FOREIGN KEY (Product_ID) REFERENCES `Products`(Product_ID);
ALTER TABLE `Product_Category` ADD CONSTRAINT Categories_Product_Category_FK FOREIGN KEY (Category_ID) REFERENCES `Categories`(Category_ID);
ALTER TABLE `Product_Category` ADD CONSTRAINT Products_Product_Category_FK FOREIGN KEY (Product_ID) REFERENCES `Products`(Product_ID);
ALTER TABLE `Product_Images` ADD CONSTRAINT Products_Product_Images_FK FOREIGN KEY (Product_ID) REFERENCES `Products`(Product_ID);
ALTER TABLE `Product_Item` ADD CONSTRAINT Products_Product_Item_FK FOREIGN KEY (Product_ID) REFERENCES `Products`(Product_ID);
ALTER TABLE `Product_Item` ADD CONSTRAINT Products_Product_Item_FK_2 FOREIGN KEY (Item_ID) REFERENCES `Products`(Product_ID);
ALTER TABLE `WishList` ADD CONSTRAINT Users_WishList_FK FOREIGN KEY (User_ID) REFERENCES `Users`(User_ID);


-- These SQL statements will drop all the old indexes and update with new indexes as needed and with a standard naming protocol

ALTER TABLE `Account` ADD INDEX `Account_Customer_ID_Idx` (`Customer_ID` );
ALTER TABLE `Account` ADD INDEX `Account_User_ID_Idx` (`User_ID` );
ALTER TABLE `Affiliates` ADD INDEX `Affiliate_AffCode_Idx` (`AffCode` );
ALTER TABLE `CardData` ADD INDEX `CardData_Customer_ID_Idx` (`Customer_ID` );
ALTER TABLE `Categories` ADD INDEX `Categories_CatCore_ID_Idx` (`CatCore_ID` );
ALTER TABLE `Categories` ADD INDEX `Category_Color_ID_Idx` (`Color_ID` );
ALTER TABLE `Categories` ADD INDEX `Category_Parent_ID_Idx` (`Parent_ID` );
ALTER TABLE `Certificates` ADD INDEX `Certificates_Cert_Code_Idx` (`Cert_Code` );
ALTER TABLE `Countries` ADD UNIQUE `Countries_Abbrev_Idx` (`Abbrev` );
ALTER TABLE `Countries` ADD INDEX `Countries_Shipping_Idx` (`Shipping` );
ALTER TABLE `Customers` ADD INDEX `Customers_User_ID_Idx` (`User_ID` );
ALTER TABLE `Discounts` ADD INDEX `Discounts_Coup_Code_Idx` (`Coup_Code` );
ALTER TABLE `Feature_Category` ADD INDEX `Feature_Category_Category_ID_Idx` (`Category_ID` );
ALTER TABLE `Feature_Category` ADD INDEX `Feature_Category_Feature_ID_Idx` (`Feature_ID` );
ALTER TABLE `Feature_Item` ADD INDEX `Feature_Item_Feature_ID_Idx` (`Feature_ID` );
ALTER TABLE `Feature_Item` ADD INDEX `Feature_Item_Item_ID_Idx` (`Item_ID` );
ALTER TABLE `Feature_Product` ADD INDEX `Feature_Product_Feature_ID_Idx` (`Feature_ID` );
ALTER TABLE `Feature_Product` ADD INDEX `Feature_Product_Product_ID_Idx` (`Product_ID` );
ALTER TABLE `Features` ADD INDEX `Features_AccessKey_Idx` (`AccessKey` );
ALTER TABLE `Features` ADD INDEX `Features_Color_ID_Idx` (`Color_ID` );
ALTER TABLE `Features` ADD INDEX `Features_User_ID_Idx` (`User_ID` );
ALTER TABLE `Groups` ADD INDEX `Groups_Name_Idx` (`Name` );
ALTER TABLE `LocalTax` ADD INDEX `LocalTax_ZipCode_Idx` (`ZipCode` );
ALTER TABLE `Locales` ADD UNIQUE `Locales_Name_Idx` (`Name` );
ALTER TABLE `Memberships` ADD INDEX `Memberships_AccessKey_ID_Idx` (`AccessKey_ID` );
ALTER TABLE `Memberships` ADD INDEX `Memberships_User_ID_Idx` (`User_ID` );
ALTER TABLE `Order_No` ADD INDEX `Order_No_Coup_Code_Idx` (`Coup_Code` );
ALTER TABLE `Order_No` ADD INDEX `Order_No_Customer_ID_Idx` (`Customer_ID` );
ALTER TABLE `Order_No` ADD INDEX `Order_No_User_ID_Idx` (`User_ID` );
ALTER TABLE `Order_PO` ADD INDEX `Order_PO_Account_ID_Idx` (`Account_ID` );
ALTER TABLE `Order_PO` ADD INDEX `Order_PO_Order_No_Idx` (`Order_No` );
ALTER TABLE `Pages` ADD INDEX `Pages_AccessKey_Idx` (`AccessKey` );
ALTER TABLE `Pages` ADD INDEX `Pages_CatCore_ID_Idx` (`CatCore_ID` );
ALTER TABLE `Pages` ADD INDEX `Pages_Color_ID_Idx` (`Color_ID` );
ALTER TABLE `ProdAddons` ADD INDEX `ProdAddons_Product_ID_Idx` (`Product_ID` );
ALTER TABLE `ProdAddons` ADD INDEX `ProdAddons_Standard_ID_Idx` (`Standard_ID` );
ALTER TABLE `Product_Category` ADD INDEX `Product_Category_Category_ID_Idx` (`Category_ID` );
ALTER TABLE `Product_Category` ADD INDEX `Product_Category_Product_ID_Idx` (`Product_ID` );
ALTER TABLE `Product_Images` ADD INDEX `Product_Images_Product_ID_Idx` (`Product_ID` );
ALTER TABLE `Product_Item` ADD INDEX `Product_Item_Item_ID_Idx` (`Item_ID` );
ALTER TABLE `Product_Item` ADD INDEX `Product_Item_Product_ID_Idx` (`Product_ID` );
ALTER TABLE `Products` ADD INDEX `Products_AccessKey_Idx` (`AccessKey` );
ALTER TABLE `Products` ADD INDEX `Products_Account_ID_Idx` (`Account_ID` );
ALTER TABLE `Products` ADD INDEX `Products_Highlight_Idx` (`Highlight` );
ALTER TABLE `Products` ADD INDEX `Products_NumInStock_Idx` (`NumInStock` );
ALTER TABLE `Products` ADD INDEX `Colors_Products_FK` (`Color_ID` );
ALTER TABLE `TempBasket` ADD INDEX `TempBasket_BasketNum_Idx` (`BasketNum` );
ALTER TABLE `TempBasket` ADD INDEX `TempBasket_Product_ID_Idx` (`Product_ID` );
ALTER TABLE `Users` ADD INDEX `Users_Account_ID_Idx` (`Account_ID` );
ALTER TABLE `Users` ADD INDEX `Users_Affiliate_ID_Idx` (`Affiliate_ID` );
ALTER TABLE `Users` ADD INDEX `Users_Customer_ID_Idx` (`Customer_ID` );
ALTER TABLE `Users` ADD INDEX `Users_Group_ID_Idx` (`Group_ID` );
ALTER TABLE `WishList` ADD INDEX `WishList_Product_ID_Idx` (`Product_ID` );
ALTER TABLE `WishList` ADD INDEX `WishList_User_ID_Idx` (`User_ID` );


ALTER TABLE `AccessKeys` DROP INDEX `Privilege_ID`;
ALTER TABLE `Account` DROP INDEX `Contact_ID`;
ALTER TABLE `Account` DROP INDEX `User_ID`;
ALTER TABLE `Affiliates` DROP INDEX `AffCode`;
ALTER TABLE `CardData` DROP INDEX `Customer_ID`;
ALTER TABLE `CatCore` DROP INDEX `CatFormat_ID`;
ALTER TABLE `Categories` DROP INDEX `CatFormat_ID`;
ALTER TABLE `Categories` DROP INDEX `color_id`;
ALTER TABLE `Categories` DROP INDEX `Highlight`;
ALTER TABLE `Categories` DROP INDEX `Parent_ID`;
ALTER TABLE `Categories` DROP INDEX `Subcategory_ID`;
ALTER TABLE `Certificates` DROP INDEX `Cert_Code`;
ALTER TABLE `Certificates` DROP INDEX `Cert_ID`;
ALTER TABLE `Countries` DROP INDEX `Abbrev`;
ALTER TABLE `Countries` DROP INDEX `Shipping`;
ALTER TABLE `Customers` DROP INDEX `User_ID`;
ALTER TABLE `Discounts` DROP INDEX `Coup_Code`;
ALTER TABLE `Feature_Category` DROP INDEX `Category_ID`;
ALTER TABLE `Feature_Category` DROP INDEX `Event_category_ID`;
ALTER TABLE `Feature_Category` DROP INDEX `Event_ID`;
ALTER TABLE `Feature_Item` DROP INDEX `Feature_ID`;
ALTER TABLE `Feature_Item` DROP INDEX `Feature_Item_ID1`;
ALTER TABLE `Feature_Item` DROP INDEX `Item_ID`;
ALTER TABLE `Feature_Product` DROP INDEX `Category_ID`;
ALTER TABLE `Feature_Product` DROP INDEX `ID`;
ALTER TABLE `Feature_Product` DROP INDEX `Item_Number`;
ALTER TABLE `Features` DROP INDEX `access_Key`;
ALTER TABLE `Features` DROP INDEX `contributor_id`;
ALTER TABLE `Features` DROP INDEX `Feature_id`;
ALTER TABLE `Features` DROP INDEX `Palette_ID`;
ALTER TABLE `Intershipper` DROP INDEX `UserID`;
ALTER TABLE `LocalTax` DROP INDEX `Local_ID`;
ALTER TABLE `LocalTax` DROP INDEX `ZipCode`;
ALTER TABLE `Locales` DROP INDEX `Name`;
ALTER TABLE `Memberships` DROP INDEX `Membership_ID`;
ALTER TABLE `Memberships` DROP INDEX `Order_ID`;
ALTER TABLE `Memberships` DROP INDEX `Privilege_ID`;
ALTER TABLE `Memberships` DROP INDEX `Product_ID`;
ALTER TABLE `Memberships` DROP INDEX `User_ID`;
ALTER TABLE `OrderSettings` DROP INDEX `BaseOrderNum`;
ALTER TABLE `Order_No` DROP INDEX `Card_ID`;
ALTER TABLE `Order_No` DROP INDEX `Cert_Code`;
ALTER TABLE `Order_No` DROP INDEX `Coup_Code`;
ALTER TABLE `Order_No` DROP INDEX `Customer_ID`;
ALTER TABLE `Order_No` DROP INDEX `ID`;
ALTER TABLE `Order_No` DROP INDEX `User_ID`;
ALTER TABLE `Order_PO` DROP INDEX `Account_ID`;
ALTER TABLE `Order_PO` DROP INDEX `Order_no_ID`;
ALTER TABLE `Order_PO` DROP INDEX `Ship_tracker_id`;
ALTER TABLE `Pages` DROP INDEX `accesskey`;
ALTER TABLE `Pages` DROP INDEX `catcore_ID`;
ALTER TABLE `Pages` DROP INDEX `Color_ID`;
ALTER TABLE `PickLists` DROP INDEX `picklist_id`;
ALTER TABLE `ProdAddons` DROP INDEX `Product_ID`;
ALTER TABLE `ProdAddons` DROP INDEX `Standard_ID`;
ALTER TABLE `ProdDisc` DROP INDEX `Product_id`;
ALTER TABLE `ProdDisc` DROP INDEX `ProdVolume_id`;
ALTER TABLE `Product_Category` DROP INDEX `Category_ID`;
ALTER TABLE `Product_Category` DROP INDEX `ID`;
ALTER TABLE `Product_Category` DROP INDEX `Item_Number`;
ALTER TABLE `Product_Images` DROP INDEX `Profile_ID`;
ALTER TABLE `Product_Images` DROP INDEX `Profile_image_id`;
ALTER TABLE `Product_Item` DROP INDEX `Category_ID`;
ALTER TABLE `Product_Item` DROP INDEX `ID`;
ALTER TABLE `Product_Item` DROP INDEX `Item_Number`;
ALTER TABLE `Products` DROP INDEX `accessKey`;
ALTER TABLE `Products` DROP INDEX `Account_ID`;
ALTER TABLE `Products` DROP INDEX `Highlight`;
ALTER TABLE `Products` DROP INDEX `mfg_account_ID`;
ALTER TABLE `Products` DROP INDEX `num_days`;
ALTER TABLE `Products` DROP INDEX `NumChoices`;
ALTER TABLE `Products` DROP INDEX `NumInStock`;
ALTER TABLE `Products` DROP INDEX `NumOptions`;
ALTER TABLE `Products` DROP INDEX `Product_ID`;
ALTER TABLE `Settings` DROP INDEX `color_id`;
ALTER TABLE `Settings` DROP INDEX `SettingID`;
ALTER TABLE `ShipSettings` DROP INDEX `freeship_shipid`;
ALTER TABLE `StdAddons` DROP INDEX `StdID`;
ALTER TABLE `StdOptions` DROP INDEX `StdID`;
ALTER TABLE `TempBasket` DROP INDEX `Basket_Idx`;
ALTER TABLE `TempBasket` DROP INDEX `Product_ID`;
ALTER TABLE `UPS_Settings` DROP INDEX `UPS_ID`;
ALTER TABLE `UserSettings` DROP INDEX `ID`;
ALTER TABLE `Users` DROP INDEX `Account_id`;
ALTER TABLE `Users` DROP INDEX `Affiliate_ID`;
ALTER TABLE `Users` DROP INDEX `Customer_ID`;
ALTER TABLE `Users` DROP INDEX `Level`;
ALTER TABLE `Users` DROP INDEX `UserID`;
ALTER TABLE `WishList` DROP INDEX `ItemNum`;
ALTER TABLE `WishList` DROP INDEX `ListNum`;
ALTER TABLE `WishList` DROP INDEX `NumDesired`;
ALTER TABLE `WishList` DROP INDEX `Product_ID`;
ALTER TABLE `WishList` DROP INDEX `User_ID`;




